[workspace]
members = ["monas-account", "monas-content", "monas-event-manager", "wasm-module-proto", "monas-filesync", "monas-state-node"]
resolver = "2"

[workspace.package]
authors = ["Monas"]
version = "0.1.0"
edition = "2021"
rust-version = "1.79"

[workspace.dependencies]
